# Generated by Django 5.0.6 on 2024-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_address_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
